name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
    - uses: actions/checkout@v2
    
    # Test
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Run tests
      run: |
        pip install -r requirements.txt
        python -c "from server import app; print('Routes:', [f'{route.path} [WebSocket]' if hasattr(route, 'endpoint') and route.endpoint.__name__ == 'websocket_endpoint' else f'{route.path} {[m for m in route.methods]}' for route in app.routes])"
        pytest -v --capture=no

    # Login to GHCR
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Build and Push
    - name: Build and push to GHCR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
