name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
    - uses: actions/checkout@v2
    
    # Test
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    # - name: Run tests
    #   run: |
    #     pip install -r requirements.txt
    #     pip install pytest
    #     pytest -v

    # - name: Run tests
    #   run: |
    #     pip install -r requirements.txt
    #     pip install pytest
    #     python -c "from server import app; print('Routes:', [f'{route.path} [{route.methods}]' for route in app.routes])"
    #     pytest -v --capture=no
  
   - name: Run tests
      run: |
        pip install -r requirements.txt
        pip install pytest
        python -c "from server import app 
        for route in app.routes:
          if hasattr(route, 'methods'):
            print(f'HTTP Route: {route.path} {route.methods}')
          else:
            print(f'WebSocket Route: {route.path}')
          "
        pytest -v --capture=no


    # Login to GHCR
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Build and Push
    - name: Build and push to GHCR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
